# example netlify.toml
[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://mediclinic-app.netlify.app"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

## more info on configuring this file: https://ntl.fyi/file-based-build-config
